### ISSUE TITLE
Stuck on infinite loop if the images/children don't have a specified size

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/react-marquee#4]
Right now the package will get stuck on an infinite loop if the images used as children don't have a set size to them.

We need to improve the package to wait for all images to load before trying to calculate all the necessary dimensions.

**Comment by andrewrubin** [comment]
Curious about this one. I agree 100%, but I also wonder if that's up to the developer implementing it. Technically, a marquee doesn't need to use images, right?
